add metadata, packaging and debugging

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,8 +10,15 @@ matrix:
 before_install:
   # Clone nonlibc repo as we depend on it but it hasn't been added to nixpkgs
   # TODO: replace this with a nix-channel instead of a download
-  - pushd ~; git clone https://github.com/siriobalmelli/nonlibc.git; popd
+  - |
+    pushd ~
+    git clone https://github.com/siriobalmelli/nonlibc.git
+    popd
 
 script:
-  - nix-build -I ~
+  - |
+    if ! nix-build -I ~; then
+        echo "build fail! nix-info follows" >&2
+        nix-shell -p nix-info --run "nix-info -m"
+    fi
 ...
